package com.konffach.app.di

import com.konffach.app.features.auth.presentation.AuthViewModel
import com.konffach.app.features.chat.data.ChatRepository
import com.konffach.app.features.chat.data.InMemoryChatRepository
import com.konffach.app.features.chat.presentation.ChatViewModel
import com.konffach.app.features.dialogs.presentation.DialogsViewModel
import dev.zacsweers.metro.Binds
import dev.zacsweers.metro.DependencyGraph
import dev.zacsweers.metro.createGraph

/**
 * Root dependency graph. ViewModel factories are generated by Metro via @AssistedInject / @AssistedFactory.
 * Repository is bound explicitly so it can be swapped (e.g. InMemory → real API) by changing binding only.
 */
@DependencyGraph
interface AppGraph {

    val authViewModelFactory: AuthViewModel.Factory
    val dialogsViewModelFactory: DialogsViewModel.Factory
    val chatViewModelFactory: ChatViewModel.Factory
    val chatRepository: ChatRepository

    @Binds val InMemoryChatRepository.bind: ChatRepository
}

fun createAppGraph(): AppGraph = createGraph()
