package com.konffach.app.di

import androidx.compose.runtime.staticCompositionLocalOf
import com.konffach.app.features.auth.ui.AuthViewModel
import com.konffach.app.features.chat.ui.ChatViewModel
import com.konffach.app.features.dialogs.ui.DialogsViewModel
import com.konffach.app.features.home.ui.HomeViewModel
import com.konffach.app.features.settings.ui.SettingsViewModel
import com.konffach.app.navigation.NavigationViewModel
import dev.zacsweers.metro.DependencyGraph
import dev.zacsweers.metro.createGraph

interface AppScope

/**
 * Root dependency graph. ViewModel factories are generated by Metro via @AssistedInject / @AssistedFactory.
 * Bindings are grouped in [CoreProviders] and [RepositoryBindings] (Binding Containers, analogous to Dagger modules).
 */
@DependencyGraph(
    AppScope::class,
    bindingContainers = [CoreProviders::class, RepositoryBindings::class],
)
interface AppGraph : AppScope {

    val navigationViewModel: NavigationViewModel
    val authViewModelFactory: AuthViewModel.Factory
    val homeViewModelFactory: HomeViewModel.Factory
    val settingsViewModelFactory: SettingsViewModel.Factory
    val dialogsViewModelFactory: DialogsViewModel.Factory
    val chatViewModelFactory: ChatViewModel.Factory
}

fun createAppGraph(): AppGraph = createGraph()

val LocalAppScope = staticCompositionLocalOf<AppGraph> {
    error("AppGraph is not provided. Make sure to wrap your root composable with a provider.")
}
